### ISSUE TITLE
Livox Tele-15

### ISSUE THREAD

**Issue by stagsz** [York-SDCNLab/Modified_livox_mapping#1]
Is this package compatible with Livox Tele-15 or just Horizon and Mid 40?

**Comment by yorklyb** [comment]
Hi, as introduced in the readme, this is just a modified version of the original livox mapping. I'm sure that this project works for livox mid lidars and the horizon lidar. Thus, suppose that the original livox mapping supports the tele-15, I believe this project also supports it. In particular, as long as the ros topic of the point cloud is '/livox/lidar', I feel like it should work as I think the scanning pattern of tele-15 and livox mid lidar are similar (just a guess based on their official website) while the tele-15 is definitely faster.

**Comment by stagsz** [comment]
Thank's for your help and work.
