### ISSUE TITLE
Invalid argument "/camera_init" passed to canTransform argument target_frame in tf2 frame_ids cannot start with a '/' like:

### ISSUE THREAD

**Issue by Rotoslider** [York-SDCNLab/Modified_livox_mapping#2]
Seems its not happy with the way it calls /camera_init

**Comment by yorklyb** [comment]
I'm not very sure when did you encounter this. Note that this version was modified for Ubuntu 20.04. If you are using another Ubuntu version, you could try the original livox_mapping(https://github.com/Livox-SDK/livox_mapping). Or you could also try to modify the loam_livox.rviz file if this error occurs when using rviz.

**Comment by RY0xm** [comment]
Hi! I also encounter the same issue using 20.04.5 this messages are generated as long as my MID40 sends data trying to find out what could be the issue, but not a programmer over here. Thanks for this York, hope can be fixed.

**Comment by RY0xm** [comment]
After playing a little bit and searching in google :P I corrected the issue in the file lasserMapping.cpp replace all the /camera_init for only camera_init , clean your workspace with the tool catkin clean and make again the catkin workspace and this solved the problem for me, also in the loam_livox.rviz change the //camera_init to only camera_init, this should make the problem dissapear, have not tried with live feed from my mid40 but now I can play the bag files with not issues.

**Comment by yorklyb** [comment]
> I feel like it is an issue caused by different rviz versions (or gazebo versions?). I think your solution is very helpful to other users who have different rviz versions from mine. Thanks for your solution! I will close this issue now.

**Comment by yorklyb** [comment]
> After playing a little bit and searching in google :P I corrected the issue in the file lasserMapping.cpp replace all the /camera_init for only camera_init , clean your workspace with the tool catkin clean and make again the catkin workspace and this solved the problem for me, also in the loam_livox.rviz change the //camera_init to only camera_init, this should make the problem dissapear, have not tried with live feed from my mid40 but now I can play the bag files with not issues.

I feel like it is an issue caused by different rviz versions (or gazebo versions?). I think your solution is very helpful to other users who have different rviz versions from mine. Thanks for your solution! I will close this issue now.
